### ISSUE TITLE
Develop slides for sept 18

### ISSUE THREAD

**Issue by sergegoussev** [sergegoussev/ESCAP_RAP_class#8]

**Comment by XtopheB** [comment]
First draft ready. Need to integrate well with demo!

**Comment by sergegoussev** [comment]
Hey @XtopheB, great chat! Below is a summary of proposed changes for your consideration:

## Intro
 
Propose we start with a summary of what RAP is - to align with what we covered on the 11th - specifically slide 7 of the presentation where we defined RAP. This will also serve as a nice review

## Practical material
We outline the main principles we will go through in detail, and then we go through them to really define each and show how this would work and really explain it so that we have good adoption. In the middle of these, we include pauses where people do exercises that we prepare so that they can anchor what they just saw (my insipiration is the [google python class which has sessions tied to exercises](https://developers.google.com/edu/python)). Note I think the excercizes should probably be more simple - so stick with https://books.toscrape.com/ that will be demoed on the static site - which keeps it easier and makes sure everyone will try to get to the same answer.
 
Specifically we follow the [RAP principles](https://nhsdigital.github.io/rap-community-of-practice/introduction_to_RAP/what_is_RAP/#rap-principles).

### Practical material, first set of principles (to be on https://sergegoussev.github.io/ESCAP_RAP_class/docs/teaching_materials/sept_18/sept_18_session.html#practical-set-one):
  * Automation - we show the idea of how a fully automated ([and mapped](https://nhsdigital.github.io/rap-community-of-practice/implementing_RAP/process_mapping/)) process without a human in the loop (unless that is off course explicitly needed) is a very robust process.
  * Modular, re-usable code - we explain the concept - and most importantly cover [functional programming](https://nhsdigital.github.io/rap-community-of-practice/training_resources/python/python-functions/#why-use-functions).
    * We could give little challenges - there are some [here](https://nhsdigital.github.io/rap-community-of-practice/training_resources/python/python-functions/#coding-challenge)
  * Code example - we show them what both mean by showing functional programming + orchestrating a set of functions 
  
*Exercize 1:* We end with a way to break out for say 15-20 minutes and try to do functional programming + orchestrate it in a simple way using say a `main()` function that calls a few `step_1()` and `step_2()`... etc functions. If people are advanced, they can stat trying to break up a scraper site that they want (i.e. start ahead to the big assignment).

### Practical material, second set of principles (to be on https://sergegoussev.github.io/ESCAP_RAP_class/docs/teaching_materials/sept_18/sept_18_session.html#practical-set-two):
* Transparency - explain the benefits of working in a transparent fashion (even if its transparent to their team members in their NSO).
* Use of open-source tools - explain how much value there is from open source compared to more proprietary programming languages
* Version control - this is where we should show them GitHub and talk about how this works. Your examples in the slides for Alice and Bob would go nicely here.

*Exercize 2 (we very likely should give the assignment but people can do it later in their own time, such as in the 1 hour session after I log off or in the afternoon session):* We get people to create a simple (private or public) repo, write some basic code, and push it. This is off course dependent on if they have Git installed on their computers. 

### Practical matrerial, third set of principles (https://sergegoussev.github.io/ESCAP_RAP_class/docs/teaching_materials/sept_18/sept_18_session.html#practical-set-three)
* Good coding practices - this one is going to be key, as it should cover:
  * Some key Python concepts - we probably don't have time to cover things in depth, but we could perhaps cover:
    * [error handling](https://nhsdigital.github.io/rap-community-of-practice/training_resources/python/logging-and-error-handling/#error-handling-in-python), 
    * perhaps we reference that we can make [visualizations](https://nhsdigital.github.io/rap-community-of-practice/training_resources/python/visualisation-in-python/)
    * perhaps [virtual environments](https://nhsdigital.github.io/rap-community-of-practice/training_resources/python/virtual-environments/why-use-virtual-environments/) as depdencies are a key thing to know, maybe a simple `requirements.txt` is the most we do here.  
    * show how to use `py` files instead of the `notebooks`
   * Note - the [Python guide on the NHS site](https://nhsdigital.github.io/rap-community-of-practice/training_resources/python/intro-to-python/) is actually quite detailed and useful guide on all this! 
   * Comments in code/i.e. [docstrings](https://peps.python.org/pep-0257/)
   * Documentation - with a demo of `.md` files that are easy to write and then render nicely in github.
   * [Diagraming](https://nhsdigital.github.io/rap-community-of-practice/implementing_RAP/process_mapping/) (part of documentation but needing to cover so that they can try it later).
* Testing - get the idea that we can create synthetic test data for each function - that way we can test that the output of each function is as it needs to be
* Peer review - show the idea and why you need it for **every** major change/refactoring. We can show people 

*Exercise 3:* We get people to expand the functions they created in *excersize 1* and *excersize 2* to add error handling and a conda environment to their git package. If the pairs practicing things are getting far, one can try to push to github, and the other can try to add an issue about it (no branches or pull requests, stick with the simpler idea) to give their feedback.

## Wrap up and next steps
Once we go through that, I propose we bring people back and cover a few more things:
* The [maturity levels of RAP](https://nhsdigital.github.io/rap-community-of-practice/introduction_to_RAP/levels_of_RAP/) - we show again that its not all or nothing
* Introduce the main assignment - to take their existing scraper and try some things over a 1 hour session say 11-12 - to strengthen their skills:
  * diagram it to document it
  * write a `markdown` file that embeds the image and describes what its doing
  * tries functional programming + a `main()` function to orchestrate the whole thing, and add some docstrings
  * add a `conda` or `requirements.txt` to the repo
  * use error handling 
 
What do you think? The slides on this can be somewhat succinct and refernece a detailed notebook that I'll make with references for each section on the https://sergegoussev.github.io/ESCAP_RAP_class/docs/teaching_materials/sept_18/sept_18_session.htm page. 

Please ping me on slack/email to let me know what you think

**Comment by XtopheB** [comment]
I have worked on the slides to follow that structure, still lacking of time to finalize this tonight but will push a version later tonight. 
Also added a bit of direct questioning of the students to provoke some reactions, keywords for each principles (alos appearing in the slides).

**Comment by sergegoussev** [comment]
Hey @XtopheB! Nice, slides are looking great and are starting to come together! 

FYI - I pushed changes to the sept 18th page to add the in-writing documentation with some examples on each of the principles as we discussed - https://sergegoussev.github.io/ESCAP_RAP_class/docs/teaching_materials/sept_18/sept_18_session.html

The idea is that these are an alternative method to slides that can be reviewed and navigated to later, plus a few of the principles have examples and visuals to get the idea across. We can skip back and forth during the session wednesday.

Let me know what you think. I still need to add the final assignment (if you think that makes sense). I can probably also flush out with code some examples for principle 6

**Comment by XtopheB** [comment]
Hi @sergegoussev 
Nice material there, and this fits very well in the course. You are right, these material could serve as reference/exercises for the future since we will not have time to cover them all. Maybe a final assessment would be useful for some participants but I'm not sure about it, there is already a lot, I think. So this really depends on your time.  
I will finish the slides today. Tomorrow (Tuesday), I will make sure that every country has git and GitHub installed so participants would be ready to practice if they want to. 
Would you be available for a quick talk later tonight (your Monday evening, my Tuesday morning) to finalize that session? I t can be around 7:30-8:30 or even later since I don't need to be present at ESCAP too early tomorrow.  Fell free to send an invite when it best fits you.

**Comment by sergegoussev** [comment]
Finished in commit ebccb78
